### ISSUE TITLE
Добавить структуру проекта

### ISSUE THREAD

**Issue by AlexanderBobryakov** [Dild114/ProjectMIPTBOT#1]
TO-BE
- настроен .github/workflows/build.yml аналогично ДЗ
- добавлен gradlew (или mavenw) + все необходимые файлы аналогично ДЗ для запуска проекта
- добавлен readme с описанием
- добавлен Main-класс с единственным main-методом

**Comment by DmitryGavelya** [comment]
Сделал структуру, добавил ci/cd
