### ISSUE TITLE
Добавить PMD-плагин

### ISSUE THREAD

**Issue by AlexanderBobryakov** [Dild114/ProjectMIPTBOT#2]
TO-BE:
- Плагин https://docs.gradle.org/current/userguide/pmd_plugin.html
- Проверить, что он запускается при build проекта и проверяет правильность написания кода (для эксперимента можно допустить какую-нибудь ошибку)
- Оповестить команду об этом плагине

**Comment by DmitryGavelya** [comment]
Добавлен PMD плагин с правилами bestpractices.xml и maven-pmd-plugin-default.xml
Полный список на этом сайте: https://maven.apache.org/plugins/maven-pmd-plugin/examples/usingRuleSets.html
